version: "3.7"

services:
  GateDEV:
    image: avosa/gate:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mango_net
    depends_on:
      - ServiceDEV
    volumes:
      - ../gate/certs:/certs:ro
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    command: ["./wait-for-it.sh", "ServiceDEV:8096", "--", "python", "app.py"]

  ServiceDEV:
      image: avosa/service:dev
      build: .
      environment:
        - RUNMODE=${RUNMODE}
        - KEYPATH=${KEYPATH}
        - HOST=${HOST}
      depends_on:
        - ThemeDEV
        - LogbookDEV
        - SecureDEV
        - ArtifactDEV
        - CommsDEV
      networks:
        - mango_net
      ports:
        - "8096:8096"
      command: ["./wait-for-it.sh", "ThemeDEV:8093", "--", "python", "app.py"]

  ThemeDEV:
    image: avosa/theme:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "8093:8093"
    networks:
        - mango_net
    depends_on:
        - FolioDEV
    volumes: 
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    command: ["./wait-for-it.sh", "FolioDEV:8090", "--", "python", "app.py"]

  FolioDEV:
    image: avosa/folio:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "8090:8090"
    networks:
      - mango_net
    volumes: 
      - ../folio/db:/db
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    depends_on:
        - RouterDEV
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

  RouterDEV:
    image: avosa/router:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "8080:8080"
    networks:
      - mango_net
    volumes: 
      - ../secure/db/sign_rsa.pub:${KEYPATH}

  LogbookDEV:
    image: avosa/logbook:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "8089:8089"
    networks:
      - mango_net
    volumes: 
      - ../logbook/db:/db
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    depends_on:
        - RouterDEV
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

  SecureDEV:
    image: avosa/secure:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=/db/sign_rsa.pub
      - HOST=${HOST}
    ports:
      - "8086:8086"
    networks:
      - "mango_net"
    volumes: 
      - ../secure/db:/db
    depends_on:
      - "AuthDEV"
    command: ["./wait-for-it.sh", "AuthDEV:8094", "--", "python", "app.py"]

  AuthDEV:
    image: avosa/auth:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    volumes: 
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    ports:
      - "8094:8094"
    networks:
      - "mango_net"
    depends_on:
      - "ThemeDEV"
    command: ["./wait-for-it.sh", "ThemeDEV:8093", "--", "python", "app.py"]

  ArtifactDEV:
    image: avosa/artifact:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "8082:8082"
    networks:
      - "mango_net"
    volumes: 
      - ../artifact/db:/db
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    depends_on:
    - "RouterDEV"
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

  CommsDEV:
    image: avosa/comms:dev
    environment:
      - RUNMODE=${RUNMODE}
      - KEYPATH=${KEYPATH}
      - HOST=${HOST}
    ports:
      - "8085:8085"
    networks:
      - mango_net
    volumes: 
      - ../comms/db:/db
      - ../secure/db/sign_rsa.pub:${KEYPATH}
    depends_on:
        - RouterDEV
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

networks:
  mango_net:
    driver: bridge